import { R_EARTH, R_MOON } from "../../physics/bodies";

const BASE_METERS_TO_SCENE_UNITS = 1 / 2_000_000;
const ORBIT_DISTANCE_VISUAL_MULTIPLIER = 4;
const PLANET_RADIUS_VISUAL_MULTIPLIER = 4;
const ROCKET_VISUAL_SIZE_DIVISOR = 5000;

export const ORBIT_METERS_TO_SCENE_UNITS =
  BASE_METERS_TO_SCENE_UNITS * ORBIT_DISTANCE_VISUAL_MULTIPLIER;
export const EARTH_RENDER_RADIUS_SCENE_UNITS =
  R_EARTH * BASE_METERS_TO_SCENE_UNITS * PLANET_RADIUS_VISUAL_MULTIPLIER;
export const MOON_RENDER_RADIUS_SCENE_UNITS =
  R_MOON * BASE_METERS_TO_SCENE_UNITS * PLANET_RADIUS_VISUAL_MULTIPLIER;
export const REFERENCE_ROCKET_RENDER_RADIUS_SCENE_UNITS =
  (R_EARTH * BASE_METERS_TO_SCENE_UNITS) / ROCKET_VISUAL_SIZE_DIVISOR;
