import { R_EARTH, R_MOON } from "../../physics/bodies";

export const ORBIT_METERS_TO_SCENE_UNITS = 1 / 2_000_000;
const PLANET_RADIUS_VISUAL_MULTIPLIER = 1;
const ROCKET_VISUAL_SIZE_DIVISOR = 5000;

export const EARTH_RENDER_RADIUS_SCENE_UNITS =
  R_EARTH * ORBIT_METERS_TO_SCENE_UNITS * PLANET_RADIUS_VISUAL_MULTIPLIER;
export const MOON_RENDER_RADIUS_SCENE_UNITS =
  R_MOON * ORBIT_METERS_TO_SCENE_UNITS * PLANET_RADIUS_VISUAL_MULTIPLIER;
export const REFERENCE_ROCKET_RENDER_RADIUS_SCENE_UNITS =
  (R_EARTH * ORBIT_METERS_TO_SCENE_UNITS) / ROCKET_VISUAL_SIZE_DIVISOR;
