import { R_EARTH, R_MOON } from "../../physics/bodies";

export const DISTANCE_SCALE = 1 / 2_000_000;
const BODY_VISUAL_SCALE = 1;
const ROCKET_VISUAL_SCALE_DIVISOR = 5000;

export const EARTH_DRAW_RADIUS = R_EARTH * DISTANCE_SCALE * BODY_VISUAL_SCALE;
export const MOON_DRAW_RADIUS = R_MOON * DISTANCE_SCALE * BODY_VISUAL_SCALE;
export const ROCKET_DRAW_RADIUS =
  (R_EARTH * DISTANCE_SCALE) / ROCKET_VISUAL_SCALE_DIVISOR;
